ska-sa/spead2

- doc/py-recv.rst
Argument is bind_hostname, not bind_host_name
Signed-off-by: Rodrigo Tobar <rtobar@icrar.org>
> Typo in spead2.recv.Stream.add_udp_reader doc

- MANIFEST.in
It dates from when the *asyncio.py files were generated, but they're now
checked in to git and thus picked up by setuptools_git.
> Remove unneeded line from MANIFEST.in

- doc/changelog.rst
- src/recv_tcp.cpp
It was manipulating the sockets without the appropriate mutex. Apart
from generally being undefined behaviour, it could manifest as trying to
double-close the socket leading to an EBADF exception, killing the
io_service thread.
Closes #78.
> Fix a race condition in TCP accept_handler

- doc/changelog.rst
- include/spead2/common_ibv.h
- include/spead2/recv_udp_ibv.h
- src/common_ibv.cpp
- src/send_udp_ibv.cpp
This has two effects:
- If epoll spuriously indicates that there is an event to read, it
prevents the worker thread throwing an exception. This seems to happen
when using a thread pool with multiple threads. I haven't yet
determined if that's a bug in Boost.Asio, in the Mellanox drivers, or
is just expected.
- If a notification is requested, but then new completion queue entries
are observed before waiting for the notification, it's possible for
the notification to just lurk in the queue and later cause an
unnecessary wakeup. I don't know if that can actually happen (it's
unclear from the documentation whether a second notification request
will cause a second notification in the completion channel), but we're
now better protected against it.
> When a completion channel is ready, consume all events from it.

- doc/changelog.rst
- doc/py-ibverbs.rst
- doc/py-recv.rst
- doc/tools.rst
- include/spead2/common_ibv.h
- include/spead2/recv_udp.h
- include/spead2/recv_udp_ibv.h
- spead2/tools/bench_asyncio.py
- spead2/tools/recv_asyncio.py
- src/common_ibv.cpp
- src/mcdump.cpp
- src/py_recv.cpp
- src/recv_udp.cpp
- src/recv_udp_ibv.cpp
- src/spead2_bench.cpp
- src/spead2_recv.cpp
This includes
- library APIs
- spead2_recv and spead_recv.py test programs
- spead2_bench and spead2_bench.py benchmark programs
- mcdump
There are also a few tweaks to interpretation of arguments in the non-verbs code-paths for consistency.
> Support unicast in ibverbs receiver paths

- .gitmodules
- .travis/script.sh
- pyproject.toml
- setup.py
Thanks to pybind/pybind11#1995, it's now possible to use pybind11 with
PEP 517 so that pip takes care of installing it in the build
environment. This removes the need to deal with git submodules.
> Update to pybind11 2.5

- gen/gen_ibv_loader.py
> Forcibly undefined ibverbs functions after including the header

- doc/changelog.rst
- doc/cpp-ibverbs.rst
- doc/migrate-3.rst
- doc/py-ibverbs.rst
- doc/py-send.rst
- include/spead2/common_ibv.h
- include/spead2/common_raw_packet.h
- include/spead2/py_common.h
- include/spead2/send_packet.h
- include/spead2/send_udp_ibv.h
- src/common_ibv.cpp
- src/common_raw_packet.cpp
- src/py_common.cpp
- src/py_send.cpp
- src/send_udp_ibv.cpp
- src/spead2/send/__init__.py
- src/spead2/send/__init__.pyi
- src/spead2/send/asyncio.pyi
- src/spead2/tools/bench_asyncio.py
- src/spead2/tools/send_asyncio.py
- src/spead2_bench.cpp
- src/spead2_send.cpp
- tests/test_passthrough.py
- tests/test_send.py
The number of constructor arguments was getting out of hand, so I've made a config object (udp_ibv_stream_config). One can now add contiguous ranges of memory to the config object, and they'll get turned into ibv_mr's, and used directly for sending.
I've made a somewhat arbitrary limit of 4 scatter-gather entries per packet, beyond which it'll fall back to the old behaviour. 2 is probably sufficient for all the critical MeerKAT use cases I can think of (headers plus one payload item); 3 will be sufficient for multiple payload items as long as they're each at least packet-sized; so 4 should be plenty.
> Add support for zero-copy send with ibverbs

- doc/changelog.rst
- doc/py-send.rst
- include/spead2/send_stream.h
- src/spead2/tools/bench_asyncio.py
- src/spead2/tools/send_asyncio.py
- src/spead2_bench.cpp
- src/spead2_send.cpp
I found some cases where it could be pretty inaccurate e.g. asking for
90 Gbps would actually yield 72 Gbps.
> Disable hardware rate limiter by default

- src/send_tcp.cpp
It was broken in the send rewrite (not yet released). socket.async_send
will only send as much data as fits in the socket buffer at the time,
while boost::asio::async_write is a wrapper function that takes care of
shovelling the entire SPEAD2 packet into the stream before triggering
the callback.
> Fix TCP/IP transmit

- src/send_udp_ibv.cpp
A couple of commits to improve the rate limiter accuracy.
When the SW limiter falls below the target rate it seems to be caused by trying to sleep for very short times, causing significant over-sleep. At some future point I might introduce another configuration parameter to control the minimum time to even try to sleep, but that's for a future version.
> Rate limit tuning

- MANIFEST.in
- doc/changelog.rst
- doc/introduction.rst
- doc/migrate-3.rst
- src/Makefile.am
- src/send_udp_ibv.cpp
- src/spead2_bench.cpp
- src/spead2_cmdline.cpp
- src/spead2_cmdline.h
- src/spead2_recv.cpp
- src/spead2_send.cpp
Each of the C++ tools (spead2_recv, spead2_send, spead2_bench) had its own command-line handling, which lead to a lot of duplication (spead2_recv and spead2_bench had options controlling receivers, spead2_send and spead2_bench had options controlling senders), and there were inconsistencies (e.g. spead2_bench was missing the --ttl option).
There is now a helper file (plus header) where command-line options are registered and which has the logic to build streams from them. Somehow this has lead to an increase in the total lines of code, but it's also brought along some capabilities that were missing, and it'll require less work to add new options in future.
This just covers the C++ tools. The Python equivalents have the same issue, but I'll leave that for a later PR. There are also some …
> Overhaul command-line handling in C++ tools

- doc/changelog.rst
- doc/py-send.rst
- include/spead2/send_stream.h
- src/py_send.cpp
- src/send_stream.cpp
- src/send_udp_ibv.cpp
- src/send_writer.cpp
- src/spead2/send/__init__.py
- src/spead2/send/__init__.pyi
- src/spead2/tools/cmdline.py
- src/spead2_cmdline.cpp
- src/spead2_cmdline.h
- tests/test_send.py
This allows for more than 2 options. An AUTO option is the default, but
currently is the same as SW (until further investigation of where the
ConnectX-5 rate limiter does and doesn't behave well).
> Replace allow_hw_rate with rate_method

- doc/cpp-ibverbs.rst
- doc/migrate-3.rst
- doc/py-ibverbs.rst
- include/spead2/send_udp_ibv.h
- src/py_send.cpp
- src/send_udp_ibv.cpp
- src/spead2/send/__init__.py
- src/spead2/send/__init__.pyi
- src/spead2/tools/cmdline.py
- src/spead2_cmdline.cpp
- src/spead2_cmdline.h
- tests/test_passthrough.py
- tests/test_send.py
And similarly for Python. Apart from being less typing, it's a slightly
better reflection as it configures the writer rather than the common
stream class.
> Rename udp_ibv_stream_config -> udp_ibv_config 

- gen/gen_loader.py
- gen/template.cpp
That's normal behaviour if it's an old version of libmlx5dv.so which
doesn't provide the mlx5dv_is_supported symbol. It just means we don't
use multi-packet receive queues, but it's not fatal.
> Don't log a warning if libmlx5dv.so could not be loaded

- doc/migrate-3.rst
- include/spead2/send_inproc.h
- src/py_send.cpp
- src/send_inproc.cpp
- tests/test_passthrough.py
It was removed in favour of get_queues (due to substream support). I've
brought it back but marked it deprecated to ease the transition to 3.0.
> Restore inproc_stream::get_queue

- doc/changelog.rst
- src/spead2_recv.cpp
- src/spead2_send.cpp
It puts random data (created from a linear congruential generator) into
the data stream, and verifies it on the receive side. This can help with
testing issues that are missed by unit tests e.g. corner cases that only
affect a small number of heaps, or that require the buffer to be
recycled before they show up.
> Add --verify option to spead2_send and spead2_recv

- src/common_memcpy.cpp
When I introduced the constexpr for the cache line size I set
cache_line_mask to an unsigned int, which caused some address
calculations to get truncated to 32 bits.
> Fix memcpy_nontemporal

- doc/changelog.rst
- src/common_thread_pool.cpp
Profiling revealed that glibc initialises an arena the first time
dynamic allocation is one in a thread, and that this was happening when
the first packet arrived. To avoid that, do a dummy initialisation as
soon as the worker thread starts.
> Avoid running arena initialisation on the hot path

- src/send_stream.cpp
It was locking the head mutex when it should have locked the tail mutex.
I discovered this when a race condition caused sending to stop, I'm
guessing because of a race condition on need_wakeup causing a wakeup to
get lost. But there would probably have been other entertaining race
conditions too.
> Lock the correct lock when sending a heap.

- doc/migrate-3.rst
> Fix typo in documentation

- doc/changelog.rst
- include/spead2/send_packet.h
- include/spead2/send_writer.h
- src/py_send.cpp
- src/send_inproc.cpp
- src/send_packet.cpp
- src/send_streambuf.cpp
- src/send_tcp.cpp
- src/send_udp.cpp
- src/send_udp_ibv.cpp
- src/send_writer.cpp
Instead of packet_generator::next_packet allocate memory to store data that it can't reference in place (the SPEAD header and item pointers), require the caller to provide memory for this. The caller can allocate memory for each packet in flight and recycle it.
A bonus benefit is that for the ibv sender, the packet generator will write the SPEAD header and item pointers directly into the payload area where it is needed, avoiding the need to copy it.
This improves send performance with 1KB packets roughly from 64 -> 86 Gb/s.
> Improve send performance by eliminating a memory allocation

- doc/changelog.rst
- include/spead2/send_writer.h
- src/send_stream.cpp
The udp_ibv writer (and possibly others) might still have callbacks
scheduled after flush() returned.
> Fix a use-after-free bug that could crash after send::stream::~stream

- doc/changelog.rst
- include/spead2/recv_udp_ibv.h
- include/spead2/recv_udp_ibv_mprq.h
The destruction order was wrong. Trying to destroy ibverbs objects that
are still referenced by other objects fails with EBUSY. The completion
queue buffer can be quite substantial (e.g. 128MB).
> Fix a memory leak when receiving with ibverbs

- doc/changelog.rst
- src/common_memcpy.cpp
It might be needed for correct ordering with write-combining memory,
such as used by gdrcopy.
> Always SFENCE at end of memcpy_nontemporal

- configure.ac
- examples/test_recv.py
- examples/test_send.py
- examples/test_send_asyncio.py
- gen/gen_loader.py
- setup.py
Out of the box, Ubuntu 20.04 has a /usr/bin/python3 but no
/usr/bin/python (and on older distributions, /usr/bin/python in Python
2). While virtual environments are preferred, using python3 for scripts
makes it possible to bootstrap and compile spead2 for C++ without
knowing much of anything about Python.
> Use 'python3' everywhere to invoke Python

- include/spead2/send_stream.h
Stub implementations of some abstract functions didn't use the
parameters, causing compiler warnings in some cases. Fix by deleting the
names of the parameters.
> Fix some compiler warnings about unused parameters

- src/recv_mem.cpp
Previously it was directly calling `stop` on the stream. This is
equivalent to the user calling it, which is normally a hard stop e.g. if
it is a ring_stream, it will stop the ringbuffer without pushing any
incomplete heaps into it, or whatever flushing a subclass has
implemented in its `stop_received` overload.
Instead, use `add_packet_state.stop`, which is what's normally called
for a stop triggered by the stream itself (for example, a stop heap or
end-of-file in a pcap file), which indirectly calls `stop_received` on
the stream.
> Fix mem_reader to stop gracefully

- doc/py-recv.rst
- include/spead2/recv_stream.h
- src/recv_stream.cpp
- src/unittest_recv_stream_stats.cpp
- tests/test_recv.py
- Add a whole bag of typedefs
- Add `count` and `at` methods
- Add reverse iterator functions
- Make indexing operations on a const stream_stats return a const
reference instead of a value
- Make operator[] with unknown name throw std::out_of_range rather than
std::invalid_argument, for consistency with `at` (in a std::map it
creates a new element, but stream_stats doesn't allow elements to be
added or removed).
> Make stream_stats (C++) more closely mimic STL classes

- doc/changelog.rst
- doc/cpp-recv-chunk.rst
- doc/cpp-recv.rst
- examples/gdrapi_example.cu
- include/spead2/common_memory_allocator.h
- include/spead2/common_memory_pool.h
- include/spead2/py_common.h
- include/spead2/recv_chunk_stream.h
- src/common_memory_allocator.cpp
- src/common_memory_pool.cpp
- src/py_common.cpp
- src/py_recv.cpp
- src/recv_chunk_stream.cpp
Previously it held a shared_ptr reference to the allocator, and called
back to the allocator to free the memory via a virtual function.
This had a few disadvantages:
- The allocator had to be kept alive (and referenced) even when its
state wasn't needed for deletion (which was pretty much all the time).
- You had to have an allocator class, which made it lots of work to
convert a regular unique_ptr to a memory_allocator::pointer.
- Any additional state had to be crammed into a void*, which had low
safety (raw pointer AND untyped).
Replace it all by having the deleter type derive from std::function.
There is still backwards-compatible support for custom allocators that
override `free` and/or expect to be able to call `get_allocator` and
`get_user` on the deleter, but the allocators defined …
> Redesign deleter for memory_allocator::pointer

- examples/gdrapi_example.cu
- include/spead2/common_memory_pool.h
- src/common_memory_pool.cpp
- src/unittest_memory_allocator.cpp
- src/unittest_memory_pool.cpp
It was updated but not tested (lack of hardware) when the memory
allocator API was changed. It broke because it tried to get the
gdrapi_memory_allocator::deleter from the pointer, but it was getting
the deleter for the memory pool.
Fixed by adding some API to memory_pool to allow the underlying deleter
to be retrieved.
> Fix gdrapi_example.cu

- src/unittest_memcpy.cpp
The whole unit testing goes from over 1 minute to under 1 second.
BOOST_CHECK_EQUAL was being called element-by-element, which for some
reason is incredibly slow. These days boost can do comparisons of arrays
(using BOOST_TEST) and it is much much faster.
> Speed up the common_memcpy unit test

- src/spead2/tools/recv_asyncio.py
- src/spead2_recv.cpp
In the Python version it was printing some bogus fields because it was
using introspection on the object. Fix by making it using the newer
dictionary-like API.
In the C++ version, replace the hardcoded list of stats fields with the
map-like API. Also fix stats being printed in hex due to cout being left
in hex mode.
> Fix bugs in reporting stats from spead2_recv

- doc/changelog.rst
- include/spead2/send_writer.h
- src/send_writer.cpp
Previously it could be a bit off because wait times were rounded to
whole nanoseconds (or whatever the unit of high_resolution_clock is).
While the actual sleeps can only be this accurate, the residual errors
would accumulate and should eventually be corrected.
This is fixed by using a new precise_time class for internal time
calculations, that holds a time_point for the high resolution clock, and
a small correction term.
> Improve accuracy of rate limiter

- .ci/install-sys-pkgs.sh
- configure.ac
- doc/changelog.rst
- doc/introduction.rst
- doc/py-recv.rst
- include/spead2/recv_stream.h
- manylinux/before_all.sh
- src/py_recv.cpp
- src/recv_stream.cpp
- src/send_writer.cpp
- src/spead2/recv/__init__.pyi
- src/spead2/tools/cmdline.py
- src/spead2_cmdline.cpp
- src/spead2_cmdline.h
- tests/test_recv.py
While there is support for the receiver to consume from multiple concurrent senders, it is always vulnerable to heap loss if one sender is much faster than another, since `max_heaps` limits the number of other heaps that can go by while waiting for one heap to be received. This feature aims to improve that by isolating the age-out mechanism to each producer.
In this first version, the producer is determined by taking the heap cnt modulo the number of substreams, which is a lightweight operation (particularly with libdivide, which is added as a dependency). It would theoretically be possible to place it under user control in future for other schemes.
> Add substreams option for receivers

- doc/changelog.rst
- src/spead2/send/asyncio.py
- tests/test_send_asyncio.py
It occurs when the future returned by `async_send_heap` or
`async_send_heaps` is cancelled before it completes.
Also fixed another potential instance with cancelling TcpStream.connect,
although it hasn't been observed yet.
> Fix an asyncio.InvalidStateError

- doc/cpp-ibverbs.rst
- doc/perf.rst
- doc/py-ibverbs.rst
- doc/tools.rst
- Add advice on tuning Epyc
- Emphasise importance of ibverbs, and clarify that the Networking
section only applies to kernel networking.
- Mention chunking receiver in application tuning.
- Update broken link to MLNX EN manual
- Update Mellanox -> NVIDIA in a number of places, and refer to ConnectX
generically rather than specific iterations.
> Improvements to tuning docs

- .github/workflows/test.yml
Set CPPFLAGS and LDFLAGS to access /usr/local/include and /usr/local/lib. Some recent ecosystem change has prevented those paths from being picked up.
Also bump all the actions to the most recent versions.
> Make CI builds work on MacOS again

- include/spead2/common_raw_packet.h
- include/spead2/recv_udp_pcap.h
- src/common_raw_packet.cpp
- src/recv_udp_pcap.cpp
- src/unittest_raw_packet.cpp
Today while trying to read a pcap dump from the Tallon correlator for SKA-MID I ran into an issue with the pcap reader not being able to read these files. After some debugging I found out that this was because the data had been captured using the "any" device, as in their experiments they send some data from a server on the loopback interface (i.e, the descriptors) and some other data from the FPGAs.
After learning the difference in the headers, I came up with these two commits that add support for cooked frames to the spead2 pcap reader. The first adds the actual parsing and unit tests, while the second uses this in the pcap reader. Note that the pcap reader didn't previously check that the frames being read were ethernet frames, and thus the problem wasn't obvious at first. A check has …
> Add Linux "cooked" mode support for pcap dump reader

- .github/workflows/test.yml
- manylinux/before_all.sh
- setup.cfg
- setup.py
This is a bit of maintenance which will allow other tools (hopefully
including dependabot) to access metadata.
It also makes the code a bit simpler, because we can use the `file:` and
`attr:` magic in setup.cfg.
> Move most of setup.py into setup.cfg

- doc/conf.py
The latter prevented asyncio.TcpStream.connect's documentation from being generated, which was confusing. Using autodoc's own mocking mechanism seems to fix this issue, and hopefully prevent future ones.
See https://spead2.readthedocs.io/en/latest/py-send.html#id2 for the current missing documentation.
Signed-off-by: Rodrigo Tobar <rtobar@icrar.org>
> Use autodoc's mocking mechanism instead of our own

- doc/changelog.rst
- doc/py-recv-chunk.rst
- doc/recv-chunk.rst
- include/spead2/recv_chunk_stream.h
- src/py_recv.cpp
- src/recv_chunk_stream.cpp
- src/spead2/recv/__init__.pyi
- src/spead2/recv/numba.py
- tests/test_recv_chunk_stream.py
Allow the place callback to emit a block of data to be placed into the chunk at a particular offset. This makes it practical to capture immediate items from the heaps.
> Support placing extra data into chunks

- doc/changelog.rst
- tests/test_send_asyncio.py
Just the two unit tests, actually.
Contributes to: NGC-899.
> Update unit tests where async tasks were unhandled

- .ci/py-tests.sh
- include/spead2/recv_chunk_stream_group.h
- src/py_recv.cpp
- tests/shutdown.py
If the process exits without explicitly stopping anything, it's possible deadlock if the threadpools used for the streams in a group were created after the group. This happens because `atexit` stops the threadpools before it stops the group.
Fix it by giving the exit_stopper treatment to
chunk_stream_group_member. Since the member is necessarily constructed after the thread pool it uses, this ensures that the member (and hence the whole group) is stopped before the thread pool.
> Fix a shutdown hang

- doc/changelog.rst
- src/spead2/tools/bench_asyncio.py
- src/spead2_bench.cpp
- Serialize and deserialize enums when sent between master and agent (this failure means it's probably crashed ever since 3.0).
- Show a helpful error when run without arguments.
- Fix spelling of "speed".
> Some fixes for spead2_bench.py

- doc/dev-recv-destruction.rst
- include/spead2/recv_stream.h
- src/recv_stream.cpp
The ibv reader was crashing due to use-after-free errors. It needed to call ibv_end_poll after the batch finished, but if a packet in the batch stopped the stream, the reader would immediately get destroyed, taking the completion queue with it.
Fix by delaying the actual stream stop until the add_packet_state object is destroyed, which gives the poller object a chance to unwind first.
> Defer reader destruction until add_packet_state destructor

- doc/changelog.rst
- manylinux/before_all.sh
- pyproject.toml
- setup.py
- Strip static symbols
- Stop boost inserting dynamic symbols, which aren't needed as we're not passing boost objects (or exceptions) across the interface boundary)
- Use link-time optimisation
> Wheel build improvements

- tests/test_passthrough.py
This avoids ResourceWarnings from pytest when run under python -X dev.
> Close custom TCP sockets

- doc/dev-recv-destruction.rst
- include/spead2/recv_inproc.h
- include/spead2/recv_stream.h
- include/spead2/recv_tcp.h
- include/spead2/recv_udp.h
- include/spead2/recv_udp_ibv.h
- src/recv_inproc.cpp
- src/recv_stream.cpp
- src/recv_tcp.cpp
- src/recv_udp.cpp
- src/recv_udp_ibv.cpp
> Defer deleting readers until stream destruction

- configure.ac
- include/spead2/common_defines.h
- include/spead2/common_features.h.in
- include/spead2/common_memcpy.h
- src/common_memcpy.cpp
This support is used so that the SSE2 version of memcpy_nontemporal is selected only if the CPU supports SSE2 at runtime.
On x86-64 there is guaranteed to be runtime support, so this only affects i386. Note that i386 is not currently tested. The real motivation is that it lays the groundwork for adding more specialised variants e.g. AVX, AVX-512, MOVDIR64B etc.
> Add detection of function multi-versioning in the compiler

- pyproject.toml
- tests/test_recv.py
This improves test coverage in a few ways:
- it tests against all the Python versions for which wheels are built (the rest of the unit tests only cover min and max versions)
- it tests the wheels rather than the source code
- once other architectures are added, those will get tests too
> Have cibuildwheel test the wheels it builds

- .github/workflows/test.yml
- configure.ac
- doc/introduction.rst
- manylinux/before_all.sh
- pyproject.toml
- setup.py
- src/Makefile.am
- tests/test_passthrough.py
- tests/test_passthrough_asyncio.py
To speed things up, the minimum Boost version is now 1.69 (close to 5 years old, so should be available in most non-EOL OSes already) and the Python build no longer requires any compiled Boost libraries (just headers).
> Build aarch64 wheels

- mypy.ini
- pyproject.toml
This keeps all the static checkers (isort, black, mypy) together, except for flake8 which refuses to use pyproject.
> Move mypy configuration into pyproject.toml

- tests/test_recv.py
- tests/test_recv_chunk_stream_group.py
A few of the tests are fundamentally non-deterministic. Add/increase sleeps to reduce the chance of tests failing. Particularly useful now that cibuildwheel is also running tests.
> Add some more sleeps to the tests

- .github/workflows/test.yml
This speeds up the latency process, even though it increases the total work (because before_all.sh now runs for every wheel, instead of once per architecture).
A new stage is added at the end to fetch the debug symbols produced for each wheel and put them into a single compressed tarball. This gets much better compression than the zipfile that Github produces for the artifact (I'm guessing because the individual files have a lot of commonality, and a .tar.xz is a compressed archive of files while .zip is an archive of compressed files.
> Build all the wheels in parallel

- meson.build
It was using the C++ compiler for detection, but the CUDA compiler when
building. They have different options to configure them (cxx_flags
versus cuda_flags).
The implementation is more complex than I would have liked, because the
cuda compiler support in meson doesn't implement has_function.
> Fix detection of gdrapi

- meson.build
Using `dependency('cuda')` is only necessary if linking CUDA into a
project that isn't using nvcc, or if using extra libs like cublas.
Neither applies here, so I've replaced cuda_dep with an empty
dependency. Dependencies are still helpful because one can use a
disabler if CUDA is not found or is disabled by user options.
> meson: simplify cuda_dep

- doc/changelog.rst
- pyproject.toml
This makes the debug info more usable, since it doesn't reference ephemeral build directories. See
https://github.com/mesonbuild/meson-python/issues/440#issuecomment-1702668770 for more info.
> Build wheels in fixed build directory on Linux

- tests/conftest.py
- tests/test_passthrough.py
- tests/test_passthrough_asyncio.py
- tests/test_recv.py
- tests/test_send.py
- tests/test_send_asyncio.py
Instead of selectively clearing members in teardown methods, just clear the whole object every time using a pytest hook.
> Use a more generic workaround for pytest-dev/pytest#11374

- include/spead2/py_common.h
- src/py_common.cpp
- src/py_recv.cpp
- src/py_send.cpp
I did some microbenching and found no evidence that the SPEAD2_PTMF wrapper was improving performance at all, compared to just passing the pointer-to-member-function to pybind11, even though the latter involves making a call via a pointer (bad for branch prediction). So I've eliminated the SPEAD2_PTMF macro entirely, and simplified SPEAD2_PTMF_VOID to use a more obvious approach. The latter also isn't needed for any const member functions so I eliminated that support too.
> Simplify wrapping of pointers to members

- src/py_recv.cpp
It used to take a buffer_info by reference and move out of it, due to limitations in the original implementation of emplace_reader (I think involving pushing the work onto a worker thread). Perfect forwarding is no longer an issue, and buffer_info is non-copyable so there is no need to worry about an accidental copy.
> Simplify buffer_reader construction

- include/spead2/py_common.h
When it was first written, compiler bugs prevented importing the base class constructor, but compilers have since improved (hopefully).
> Simplify thread_pool_wrapper constructor

- doc/cpp-send.rst
- doc/dev-setup.rst
- doc/migrate-3.rst
- doc/py-logging.rst
- doc/tools.rst
While `code` seems to work, Sphinx documents `code-block`, and an alias `sourcecode`.
> Change .. code:: to .. code-block:: in Sphinx docs

- doc/conf.py
Readthedocs can now build the full module, so it's not necessary.
> Don't mock in documentation

- doc/dev-debug.rst
Noticed it while reading through the dev documentation.
> Fix typo in dev-debug.rst

- src/spead2/send/__init__.pyi
- Remove the old constructor which took a hostname and port (it was removed in spead2 4.0)
- Ensure that buffer_size is correctly handled for all the constructors that use it. This required duplicating each overload to handle two cases: if the following required arguments are passed positionally then config and buffer_size are required; if they are passed as kwargs then config and buffer_size are optional.
> Fix type annotations for send.UdpStream constructors

- include/spead2/send_stream.h
- src/meson.build
- src/unittest_send_completion.cpp
When using a completion token rather than a callback function, the boolean return is no longer available. Unfortunately this requires having two overloads.
Using this with boost::asio::use_future will greatly simplify the common case of sending a heap then at a later point blocking until it is sent or throwing if there was a problem.
> Make async_send_heap and async_send_heaps work with completion tokens

- include/spead2/send_packet.h
- src/py_send.cpp
- src/send_packet.cpp
- src/send_writer.cpp
Previously it returned a new vector, which was then assigned over a previous vector. That means incrementally allocating memory for the new vector, then freeing the original vector. It's more efficient to keep reusing the same vector object, which quickly grows to the size it needs to be, then doesn't require any further memory allocation.
This can improve throughput for 1472-byte packets by 20%.
> Make packet_generator::next_packet work in-place

- include/spead2/recv_inproc.h
- include/spead2/recv_udp_ibv.h
- src/recv_inproc.cpp
- src/recv_udp.cpp
- src/send_udp.cpp
- src/send_udp_ibv.cpp
Replace it with async_wait, which more directly captures the intent.
> Eliminate deprecated boost::asio::null_buffers

- doc/py-recv.rst
- src/py_common.cpp
- src/spead2/__init__.pyi
- MmapAllocator has an optional second parameter (prefer_huge)
- MemoryPool's allocator is an optional argument.
> Fix a couple of Python bindings for custom allocators

- .ci/before_all_linux.sh
- .ci/before_all_macos.sh
The aarch64 manylinux builds have started failing with errors about not trusting the certificate for www.tcpdump.org, and that doesn't seem to be a problem for curl. I've also had issues with wget and certificates in the past (https://github.com/pypa/manylinux/issues/1203), so I'm ditching it and going back to curl. It might be flakier since curl doesn't automatically retry if the connection drops partway through (it has a --retry option but that only retries on HTTP status codes that indicate a transient error).
> CI: use curl for downloads instead of wget

- .ci/before_all_linux.sh
- .ci/before_all_macos.sh
This is necessitated by boost@1.83 disappearing from homebrew.
> Update boost to 1.84 for building wheels

- .github/workflows/test.yml
It was previous using the `master` branch, but the repo now has a more recent `main` branch. Rather than deal with that mess, just switch to a tagged release. This will hopefully address the warnings about node v16 being deprecated.
> Switch to coverallsapp/github-action@v2.2.3

- doc/changelog.rst
- doc/py-ibverbs.rst
- requirements-3.12.txt
- requirements.in
- requirements.txt
- setup.cfg
- tests/test_passthrough.py
netifaces is deprecated.
netifaces2 seems to have non-deterministic iteration order, which was causing the senders and receivers in TestPassthroughUdp6Multicast to use a different interface. Fix by adding @functools.lru_cache to cache the result after the first call.
> Switch to netifaces2

- .ci/all-builds.sh
- doc/changelog.rst
- include/spead2/common_features.h.in
- include/spead2/recv_udp.h
- meson.build
- meson.options
- src/recv_udp.cpp
GRO allows a socket to opt in to having the kernel group together packets with the same header information (source, destination, size etc) into one jumbo packet. The original packet size is provided as ancillary data to allow userspace to reconstruct the original packets. This can provide around a 20% speedup.
> Implement support for generic receive offload

- .ci/before_all_macos.sh
- .ci/install-sys-pkgs.sh
- .github/workflows/test.yml
- pyproject.toml
- src/common_memory_pool.cpp
- Run tests on macos-14 (Apple Silicon)
- Build x86_64 wheels on macos-13 and arm64 wheels on macos-14, so that
you're doing native builds in each case. This simplifies the
installation of libpcap since it's no longer necessary to cross-build
it, and allows the arm64 wheels to be tested.
- Create a meson 'native' file which tells the compiler where to find
Boost, includes and libraries on Homebrew. This is needed for Apple
Silicon builds because Homebrew stuff goes into /opt/homebrew and the
tools don't know about that.
- Update cibuildwheel to 2.17.0
- Unify some code between .ci/install-sys-pkgs.sh and
.ci/before_all_macos.sh.
One regression with this change is that Python 3.8 wheels are no longer
produced for Apple Silicon. I'm guessing that this configuration is not
going to be in …
> Update CI builds on MacOS

- .pre-commit-config.yaml
- requirements-3.12.txt
- requirements-readthedocs.txt
- src/spead2/__init__.py
- np.lib.utils.safe_eval has been removed in favour of ast.literal_eval
- np.array(..., copy=False) now errors out if a copy is required, whereas numpy 1.x would fall back to copying. We were depending on the fallback.
- Encoding floats on the slow path was incorrectly mixing numpy scalars into what should have been a pure Python calculation. It's not clear how this wasn't failing on numpy 1.26, which doesn't allow bitwise OR between np.uint64 and Python scalars.
> Fix incompatibilities with numpy 2.0

- .ci/install-sys-pkgs.sh
This is needed to install netifaces2 for testing.
> Fix Rust installation in MacOS 14 builds

- .readthedocs.yml
- doc/conf.py
- requirements-readthedocs.in
- requirements-readthedocs.txt
Use sphinxcontrib-svg2pdfconverter to convert SVG images to PDF for inclusion in the PDF build.
> Fix PDF docs build

- pytest.ini
There was a warning with it missing.
> Add asyncio_default_fixture_loop_scope to pytest.ini

- .ci/Dockerfile
- .ci/install-sys-pkgs.sh
- .ci/setup-flags.sh
- Jenkinsfile
- Move venv creation back to Jenkinsfile, and create it inside the workspace
- Remove native.ini for Linux and use it on MacOS only
- Update Jenkins install step to use setup-flags.sh.
> Rework for Jenkins testing

- .ci/Dockerfile
- Dockerfile.CI
- Jenkinsfile
The Jenkins job on our new deployment is running Docker containers with the option `-u 1000:1000` instead of `-u 0:0` which results in permissions issues when doing administrative things such as using `apt-get` to install stuff.
So this commit moves the install stages of the test run into a Dockerfile, so that the image which is all nicely configured can then be used to run the tests.
Relates to NGC-1447.
> Shift a couple of stages from Jenkinsfile into Dockerfile

- .ci/Dockerfile
- .ci/py-tests-jenkins.sh
setpriv isn't quite as convenient to use as spead2_net_raw (being more general purpose), but it has the advantage of already being installed and hence we don't need to mess around compiling the spead2 C++ tool suite.
> Jenkins: try to obtain cap_net_raw

- requirements-readthedocs.txt
I don't think it should matter (we're not using Jinja's sandbox or untrusted inputs) but this should keep dependabot happy.
> Bump jinja2 to 3.1.5

- .readthedocs.yml
See https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
> Update .readthedocs.yml for new requirement

- .ci/install-sys-pkgs.sh
- .github/workflows/test.yml
This should speed things up significantly
Also build cibuildwheel to 2.23.0, which officially supports these
runners.
> Use native ARM runners for building aarch64 wheels

- .ci/before_all_linux.sh
- .github/workflows/test.yml
- pyproject.toml
Previous versions used a GHA API that's been sunset.
> Bump sccache to the latest version

- tests/test_passthrough.py
In particular, this ensures that testing the ibv support on a system without working multicast loopback will time out fairly quickly instead of hanging forever.
> Add more pytest.mark.timeout

- pyproject.toml
This can be done now that Meson-python supports PEP 639.
> Make license information PEP 639-compliant
